import type { KnipConfig } from "knip";

/**
 * Knip configuration.
 * @see https://knip.dev/overview/configuration
 */
const knipConfig: KnipConfig = {
  entry: ["src/routes/**/*.{ts,tsx}", "src/router.tsx"],
  project: ["src/**/*.{ts,tsx,css}"],
  ignoreExportsUsedInFile: true,
  ignore: ["src/routeTree.gen.ts"],
  // routeTree.gen.ts is auto-generated by TanStack Router
  ignoreUnresolved: ["./routeTree.gen"],
  tags: ["-knipignore"],
};

export default knipConfig;
